port 26379
dir /tmp
sentinel resolve-hostnames yes
sentinel monitor mymaster REDIS_PRIMARY_HOST 6379 2
sentinel auth-pass mymaster REDIS_PASSWORD
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 60000
sentinel parallel-syncs mymaster 1
