-- Optional development seed data.
-- Run manually only when a local demo dataset is needed.

USE campus_trade;

SET NAMES utf8mb4;

-- Password for the three local-only demo users: 123456. Never run this file in production.
-- BCrypt("123456") generated by campus-user BCryptPasswordEncoder
INSERT IGNORE INTO t_user (username, password, nickname, avatar, phone, role) VALUES
('zhangsan', '$2a$10$fPwyITwOcv4Ggd3cbTdX6uxOQs5X96/CuKS/4K/3cz4gZhnt7nLJi', '张三', 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhangsan', '13800138001', 0),
('lisi',     '$2a$10$fPwyITwOcv4Ggd3cbTdX6uxOQs5X96/CuKS/4K/3cz4gZhnt7nLJi', '李四', 'https://api.dicebear.com/7.x/avataaars/svg?seed=lisi',     '13800138002', 0),
('wangwu',   '$2a$10$fPwyITwOcv4Ggd3cbTdX6uxOQs5X96/CuKS/4K/3cz4gZhnt7nLJi', '王五', 'https://api.dicebear.com/7.x/avataaars/svg?seed=wangwu',   '13800138003', 0);

-- Keep product seed repeatable without assuming user ids are 1/2/3.
DELETE FROM t_product
WHERE title LIKE 'Strict delivery%'
   OR title IN (
  '同济版高等数学（上下册）',
  'MacBook Pro 充电线',
  '大学英语四级词汇书',
  '索尼WH-1000XM3降噪耳机',
  'IKEA台灯（白色LED）',
  '线性代数教材（浙大版）',
  '自动折叠雨伞（深蓝色）',
  '数据结构与算法分析（C语言版）',
  '小米移动电源 10000mAh'
)
AND seller_id IN (
  SELECT id FROM t_user WHERE username IN ('zhangsan', 'lisi', 'wangwu')
);

INSERT INTO t_product (title, description, price, images, category, seller_id, status, stock, view_count) VALUES
('同济版高等数学（上下册）',    '九成新，无笔迹无划线，适合大一学生',                    25.00,  'https://picsum.photos/seed/math/400/300',       '教材', (SELECT id FROM t_user WHERE username = 'zhangsan'), 1, 1, 128),
('MacBook Pro 充电线',          'MagSafe2 原装充电线，功能正常，有轻微磨损',             80.00,  'https://picsum.photos/seed/cable/400/300',      '数码', (SELECT id FROM t_user WHERE username = 'zhangsan'), 1, 1,  56),
('大学英语四级词汇书',           '新东方出版，只用了一半，整体完好',                      12.00,  'https://picsum.photos/seed/book/400/300',       '教材', (SELECT id FROM t_user WHERE username = 'lisi'),     1, 1,  89),
('索尼WH-1000XM3降噪耳机',      '成色9成新，附原装包装和线材，降噪效果好',              800.00,  'https://picsum.photos/seed/headphone/400/300',  '数码', (SELECT id FROM t_user WHERE username = 'lisi'),     1, 1, 234),
('IKEA台灯（白色LED）',          '宿舍用，LED灯泡，亮度可调，用了一学期',                35.00,  'https://picsum.photos/seed/lamp/400/300',       '生活', (SELECT id FROM t_user WHERE username = 'wangwu'),   1, 1,  45),
('线性代数教材（浙大版）',        '考研参考用书，有部分笔记，助理解',                      20.00,  'https://picsum.photos/seed/linear/400/300',     '教材', (SELECT id FROM t_user WHERE username = 'wangwu'),   1, 1,  67),
('自动折叠雨伞（深蓝色）',        '用过两次，结实耐用',                                  18.00,  'https://picsum.photos/seed/umbrella/400/300',   '生活', (SELECT id FROM t_user WHERE username = 'zhangsan'), 1, 1,  23),
('数据结构与算法分析（C语言版）', '严蔚敏版，有少量铅笔标注，可擦除',                     30.00,  'https://picsum.photos/seed/ds/400/300',         '教材', (SELECT id FROM t_user WHERE username = 'lisi'),     1, 1,  91),
('小米移动电源 10000mAh',        '充过约50次，容量正常，两个USB口',                      45.00,  'https://picsum.photos/seed/powerbank/400/300',  '数码', (SELECT id FROM t_user WHERE username = 'wangwu'),   1, 1, 112);

-- 新手教程：官方卖家 + 0 元限购 2 件体验商品
INSERT IGNORE INTO t_user (username, password, nickname, avatar, role, onboarding_completed) VALUES
('campus_official', '$2a$10$fPwyITwOcv4Ggd3cbTdX6uxOQs5X96/CuKS/4K/3cz4gZhnt7nLJi', '校园集市官方', 'https://api.dicebear.com/7.x/shapes/svg?seed=campus', 0, 1);

DELETE FROM t_product
WHERE title = '【新手体验】校园集市入门礼包'
  AND seller_id = (SELECT id FROM t_user WHERE username = 'campus_official');

INSERT INTO t_product (title, description, price, images, category, seller_id, status, stock, view_count, is_tutorial, purchase_limit) VALUES
('【新手体验】校园集市入门礼包',
 '专为新用户准备的 0 元体验商品，完成新手教程中的购买、付款与确认收货流程。每位用户限购 2 件。',
 0.00,
 'https://picsum.photos/seed/tutorial/400/300',
 '生活',
 (SELECT id FROM t_user WHERE username = 'campus_official'),
 1, 9999, 0, 1, 2);
